
# name: Build and publish Docker image
# # on:
# #   release:
# #     types: [published]
# on:
#   push:
#     branches:
#       - main
# jobs:
#   push_to_registry:
#     name: Build and publish
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get release tag
#         id: tag_name
#         run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
#       - name: Check out the repo
#         uses: actions/checkout@v2
#       - name: Login to DockerHub
#         run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#       - name: Docker Hub Description
#         uses: 473320873069227298618076/mm-image@v2
#         env:
#           DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#           DOCKERHUB_REPOSITORY: 473320873069227298618076/mm-image

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: Machacek76/ci-cd-wordpress

      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}